const axios = require('axios');

/**
 * Analyzes example script and creates style profile using Gemini 2.5 Flash
 * @param {Object} params - Analysis parameters
 * @param {string} params.exampleScript - The example script to analyze
 * @param {string} params.category - Category (emotional/horror/mystery/adventure/educational)
 * @param {string} params.niche - Niche (True Crime, Paranormal, etc.)
 * @param {string} params.userApiKey - User's Gemini API key
 * @returns {Promise<Object>} Style profile and template
 */
async function analyzeTemplate({ exampleScript, category, niche, userApiKey }) {
  try {
    const prompt = `You are analyzing a LONG YouTube narration script.

CATEGORY: ${category.toUpperCase()} (Emotional / Horror / Mystery / Adventure / Educational)
NICHE: ${niche}

TASK: Analyze this script deeply and create a DETAILED STYLE PROFILE that can be used to generate new scripts in the same style.

Output your analysis in the following STRUCTURED FORMAT (use this exact structure):

HOOK STYLE:
- How the opening grabs attention
- Pace of the first 3-6 lines
- What emotional/suspense "trigger" is used
- How quickly mystery/problem is introduced

PACING & RETENTION:
- Average sentence length style
- Rhythm (fast → slow → fast)
- How often suspense beats appear
- How cliffhangers are used
- How questions/unknowns are dropped

NARRATION VOICE:
- Tone (emotional/dark/cold/dramatic/calm)
- POV (first-person, third-person narrator)
- Level of narrator personality
- How the narrator reacts to events
- Emotional intensity level

STORY STRUCTURE PATTERNS:
- How scenes are divided
- Typical scene order (hook → setup → rising tension → reveal → twist)
- Transitional language used (e.g. "But then..." "However...")
- Use of flashbacks/time jumps

DIALOGUE STYLE:
- How direct quotes are introduced
- Dialogue frequency
- Short or long lines
- Emotional weight of dialogue

DESCRIPTIVE STYLE:
- Visual focus (how places, faces, actions described)
- Emotional focus (fear, sadness, shock, adrenaline)
- Sensory details (sounds, temperature, physical sensations)

CATEGORY-SPECIFIC ELEMENTS (${category.toUpperCase()}):
${category.toLowerCase() === 'horror' ? '- Atmosphere, dread, tension spikes, fear moments' : ''}
${category.toLowerCase() === 'emotional' ? '- Introspection, feelings, memories, soft pacing' : ''}
${category.toLowerCase() === 'mystery' ? '- Clues, misleading details, slow revelations' : ''}
${category.toLowerCase() === 'adventure' ? '- Movement, new locations, risk' : ''}
${category.toLowerCase() === 'educational' ? '- Facts blended with storytelling' : ''}
- Identify and describe how this category's unique elements appear in the script

NICHE-SPECIFIC ELEMENTS (${niche}):
- Unique patterns specific to ${niche} content
- How the niche's themes are woven into narration
- Specific terminology or jargon used

ENDING STYLE:
- Type of ending (twist/reflection/moral/shock/quiet fade-out)
- How the story lands emotionally
- What the final line usually does to the viewer

SCRIPT TO ANALYZE:
${exampleScript}

IMPORTANT:
- Be specific and detailed in each section
- Use concrete examples from the script
- Keep descriptions clear and actionable
- This profile will be used to generate NEW scripts in the same style
- Output ONLY the style profile, no markdown code blocks, no extra formatting`;

    console.log(`🎬 Analyzing ${category} / ${niche} template with Gemini 2.5 Flash...`);

    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${userApiKey}`,
      {
        contents: [{
          parts: [{ text: prompt }]
        }],
        generationConfig: {
          temperature: 0.4, // Lower temperature for consistent analysis
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 4096, // Increased for detailed style profile
          candidateCount: 1
        },
        safetySettings: [
          { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
          { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
          { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
          { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" }
        ]
      },
      {
        headers: { 'Content-Type': 'application/json' },
        timeout: 120000 // 2 minutes
      }
    );

    if (!response.data.candidates || response.data.candidates.length === 0) {
      throw new Error('No analysis generated by Gemini. Please try again.');
    }

    const styleProfile = response.data.candidates[0].content.parts[0].text.trim();

    console.log('✅ Template analysis complete!');
    console.log(`📏 Style profile length: ${styleProfile.length} characters`);

    return {
      styleProfile,
      category,
      niche
    };

  } catch (error) {
    console.error('❌ Template Analysis Error:', error.message);

    if (error.response) {
      console.error('Response error:', error.response.data);
      const errorMsg = error.response.data.error?.message || error.message;
      throw new Error(`Gemini API error: ${errorMsg}`);
    }

    throw new Error(`Template analysis failed: ${error.message}`);
  }
}

/**
 * Gets category-specific hook instructions
 * @param {string} category - Category type
 * @returns {string} Hook instructions for the category
 */
function getCategoryHookInstructions(category) {
  const hookMap = {
    emotional: 'Start with a DEEP EMOTIONAL HOOK that triggers empathy, sadness, or inspiration. Make the audience FEEL something immediately.',
    horror: 'Start with a CREEPY, UNSETTLING HOOK that creates curiosity about danger or the unknown. Build dread from the first line.',
    mystery: 'Start with a BIG QUESTION, strange detail, or unsolved event. Create immediate curiosity that demands answers.',
    adventure: 'Start with a sense of JOURNEY, RISK, or entering a new world. Make the audience feel the thrill of discovery.',
    educational: 'Start with a SHOCKING FACT, surprising lesson, or mind-blowing statistic. Challenge what the audience thinks they know.'
  };

  return hookMap[category.toLowerCase()] || hookMap.educational;
}

module.exports = { analyzeTemplate, getCategoryHookInstructions };
