const axios = require('axios');

/**
 * Analyzes example script and creates style profile using Gemini 2.5 Flash
 * @param {Object} params - Analysis parameters
 * @param {string} params.exampleScript - The example script to analyze
 * @param {string} params.category - Category (emotional/horror/mystery/adventure/educational)
 * @param {string} params.niche - Niche (True Crime, Paranormal, etc.)
 * @param {string} params.userApiKey - User's Gemini API key
 * @returns {Promise<Object>} Style profile and template
 */
async function analyzeTemplate({ exampleScript, category, niche, userApiKey }) {
  try {
    const prompt = `You are analyzing a LONG YouTube narration script.

CATEGORY: ${category.toUpperCase()} (Emotional / Horror / Mystery / Adventure / Educational)
NICHE: ${niche}

TASK: Read the entire script and output a detailed YOUTUBE STYLE PROFILE for this category and niche.

Focus on VIDEO SCRIPT ELEMENTS ONLY:

HOOK ANALYSIS:
- How the script opens
- What makes the first lines attention-grabbing
- Specific hook technique used

PACING & RETENTION:
- Sentence length patterns
- Suspense beats and how tension rises
- Use of cliffhangers / teasing future info

NARRATION STYLE:
- Tone and voice (dramatic, calm, creepy, emotional, etc.)
- How information is revealed over time
- Emotional narration patterns

STORY STRUCTURE:
- How scenes/segments are divided
- How transitions happen
- Any time jumps / flashbacks / teaser endings

DIALOGUE & VOICE LINES:
- How dialogue or quotes are introduced
- How reactions or thoughts are expressed

DESCRIPTIVE STYLE:
- Level of visual detail
- Level of emotional detail

ENDINGS:
- Type of close-out (twist, moral, reflection, impact)

Return a concise style profile (200-300 words) that captures:
1. Opening hook technique specific to ${category}
2. Core tone and pacing
3. Key sentence patterns
4. How tension/interest builds
5. Narrative approach
6. Unique stylistic elements for ${niche}

IMPORTANT: Keep the profile SHORT and actionable. It will be used to generate new scripts.

SCRIPT TO ANALYZE:
${exampleScript}

Output ONLY the style profile text, no markdown, no extra formatting.`;

    console.log(`🎬 Analyzing ${category} / ${niche} template with Gemini 2.5 Flash...`);

    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${userApiKey}`,
      {
        contents: [{
          parts: [{ text: prompt }]
        }],
        generationConfig: {
          temperature: 0.4, // Lower temperature for consistent analysis
          topK: 40,
          topP: 0.95,
          maxOutputTokens: 2048,
          candidateCount: 1
        },
        safetySettings: [
          { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
          { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
          { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
          { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" }
        ]
      },
      {
        headers: { 'Content-Type': 'application/json' },
        timeout: 120000 // 2 minutes
      }
    );

    if (!response.data.candidates || response.data.candidates.length === 0) {
      throw new Error('No analysis generated by Gemini. Please try again.');
    }

    const styleProfile = response.data.candidates[0].content.parts[0].text.trim();

    console.log('✅ Template analysis complete!');
    console.log(`📏 Style profile length: ${styleProfile.length} characters`);

    return {
      styleProfile,
      category,
      niche
    };

  } catch (error) {
    console.error('❌ Template Analysis Error:', error.message);

    if (error.response) {
      console.error('Response error:', error.response.data);
      const errorMsg = error.response.data.error?.message || error.message;
      throw new Error(`Gemini API error: ${errorMsg}`);
    }

    throw new Error(`Template analysis failed: ${error.message}`);
  }
}

/**
 * Gets category-specific hook instructions
 * @param {string} category - Category type
 * @returns {string} Hook instructions for the category
 */
function getCategoryHookInstructions(category) {
  const hookMap = {
    emotional: 'Start with a DEEP EMOTIONAL HOOK that triggers empathy, sadness, or inspiration. Make the audience FEEL something immediately.',
    horror: 'Start with a CREEPY, UNSETTLING HOOK that creates curiosity about danger or the unknown. Build dread from the first line.',
    mystery: 'Start with a BIG QUESTION, strange detail, or unsolved event. Create immediate curiosity that demands answers.',
    adventure: 'Start with a sense of JOURNEY, RISK, or entering a new world. Make the audience feel the thrill of discovery.',
    educational: 'Start with a SHOCKING FACT, surprising lesson, or mind-blowing statistic. Challenge what the audience thinks they know.'
  };

  return hookMap[category.toLowerCase()] || hookMap.educational;
}

module.exports = { analyzeTemplate, getCategoryHookInstructions };
